name: Build Opera Proxy for MT7621

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download SDK
      run: |
        wget https://downloads.openwrt.org/releases/24.10.2/targets/ramips/mt7621/openwrt-sdk-24.10.2-ramips-mt7621_gcc-15.1.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-24.10.2-ramips-mt7621_*.tar.xz
        mv openwrt-sdk-24.10.2-ramips-mt7621* sdk

    - name: Add opera-proxy package
      run: |
        cp -r opera-proxy sdk/package/opera-proxy
        cd sdk/package/opera-proxy
        ./update.sh

    - name: Build .ipk
      run: |
        cd sdk
        make package/opera-proxy/compile V=s -j$(nproc)

    - name: Upload .ipk
      uses: actions/upload-artifact@v3
      with:
        name: opera-proxy
        path: sdk/bin/packages/mipsel_24kc/base/opera-proxy_*.ipk
