#!/bin/sh /etc/rc.common
# Copyright (C) OpenWrt.org

USE_PROCD=1
START=40
STOP=89

PROG=/usr/bin/opera-proxy

start_service() {
    config_load opera-proxy
    config_foreach start_instance instance
}

start_instance() {
    local name="$1"

    config_get enabled "$name" enabled
    [ "$enabled" = "1" ] || return

    config_get args "$name" args

    procd_open_instance "$name"
    procd_set_param command "$PROG" $args
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance
}
